name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Prepare Project
      run: bash setup-dev.sh

    - name: Static code analysis
      run: |
        ./gradlew checkstyle
        ./gradlew detekt

    - name: Build
      run: 
        ./gradlew assembleDebug
        
    - name: Test
      run: 
        echo "TODO"
