name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Static code analysis
      run: |
        ./gradlew checkstyle
        ./gradlew detekt

    - name: Build
      run: 
        echo "TODO"
        
    - name: Test
      run: 
        echo "TODO"
